server {
    server_name meet.avaxcoolyeti.com;
    location / {
        proxy_pass http://localhost:8000;
    }

     location /xmpp-websocket {
        proxy_pass http://localhost:8000;

        # WebSocket-specific headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Forward the host header for proper origin handling
        proxy_set_header Host $host;
    }
}