#!/bin/bash

echo "============================================"
echo "Docker Hub Push Script for mowsen/jitsi-meet"
echo "============================================"
echo ""
echo "Your Docker image has been built successfully!"
echo "Image name: mowsen/jitsi-meet:latest"
echo ""
echo "To push this image to Docker Hub, run the following commands:"
echo ""
echo "1. Login to Docker Hub:"
echo "   docker login -u mowsen"
echo ""
echo "2. Push the image:"
echo "   docker push mowsen/jitsi-meet:latest"
echo ""
echo "3. (Optional) Tag with a version:"
echo "   docker tag mowsen/jitsi-meet:latest mowsen/jitsi-meet:v1.0.0"
echo "   docker push mowsen/jitsi-meet:v1.0.0"
echo ""
echo "============================================"
